### ISSUE TITLE
Comissão

### ISSUE THREAD

**Issue by phcfranca2** [Prof-Calebe/Source-Code-Inspection#114]
**PapelMoeda.java**
getValor e getQuantidade estão incompletos, falta a presença dos respectivos metodos "set".

**Comment by phcfranca2** [comment]
![image](https://user-images.githubusercontent.com/64604695/160216776-c8f1377d-bf81-435e-ba44-40b272aea03f.png)

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
