### ISSUE TITLE
Catálogo

### ISSUE THREAD

**Issue by lucasmackenzie** [Prof-Calebe/Source-Code-Inspection#116]
Cliente não solicita troco

**Comment by lucasmackenzie** [comment]
Ator não pode estar incluído no sistema

**Comment by lucasmackenzie** [comment]
Há uma ordem incorreta na parte dos pedidos. Sendo correta na ordem : solicita bilhete, inseri dinheiro, sistema solicita troco.

**Comment by lucasmackenzie** [comment]
No solicita troco, há um erro que é corrigido utilizando o extend no inserir dinheiro, e não podendo haver ligação com o cliente, sendo explicado com há ou não troco.

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
