### ISSUE TITLE
Código troco

### ISSUE THREAD

**Issue by lucasmackenzie** [Prof-Calebe/Source-Code-Inspection#123]
Não há definição do atributo papeis  no atributo de classe. Na linha 11

**Comment by lucasmackenzie** [comment]
Lógica está sendo executada no construtor na linha 13

**Comment by lucasmackenzie** [comment]
Não há métodos set para valores e quantidades. Linha 21

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
