### ISSUE TITLE
Erro de comissão: parâmetro valor está especificado nos requisitos com nome de precoDoBilhete

### ISSUE THREAD

**Issue by matteo11-bruge** [Prof-Calebe/Source-Code-Inspection#128]
https://github.com/Prof-Calebe/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java#L17

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
