### ISSUE TITLE
Erro de computação: o índice 1 de papeisMoeda será sobreposto, e o índice 0 ficará sem valor

### ISSUE THREAD

**Issue by matteo11-bruge** [Prof-Calebe/Source-Code-Inspection#131]
https://github.com/Prof-Calebe/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/Troco.java#L44

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
