### ISSUE TITLE
Falta de JvaDoc no nivel da classe, deve ser explicado

### ISSUE THREAD

**Issue by leticia-cyber** [Prof-Calebe/Source-Code-Inspection#196]
https://github.com/Prof-Calebe/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/PapelMoeda.java#L8

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
