### ISSUE TITLE
ISSUES

### ISSUE THREAD

**Issue by MarcosVitorCS** [Prof-Calebe/Source-Code-Inspection#197]
Defeito na comparação de papel moeda

Link: Linha 25
Descrição: O loop for na função inserir está comparando o índice 1 do array papelMoeda ao invés do valor atual (papelMoeda[i]) com a quantidade inserida.
Label: Bug, Lógica
Valor do saldo não está sendo deduzido após a impressão

Link: Linha 39
Descrição: Depois de imprimir o ticket, o saldo não está sendo subtraído do valor do ticket.
Label: Bug, Lógica
Método getTroco() retorna null

Link: Linha 33
Descrição: O método getTroco() está retornando null, mas deveria retornar um Iterator<Integer> contendo o troco, caso exista.
Label: Bug, Implementação
Variável valor não está sendo usada para calcular o troco

Link: Linha 12
Descrição: A variável valor é declarada, mas não está sendo utilizada para calcular o troco ou validar o saldo.
Label: Bug, Implementação
Erro na condição de busca de papel moeda válido

Link: Linhas 20-22
Descrição: A condição dentro do loop de busca por papel moeda válido (papelMoeda[1] == quantia) sempre compara com o segundo elemento do array papelMoeda, deveria ser papelMoeda[i].
Label: Bug, Lógica
Falta de tratamento para saldo negativo após impressão

Link: Linha 39
Descrição: Após a impressão do ticket, caso o saldo seja maior que o valor do ticket, não há tratamento para o saldo negativo.
Label: Bug, Lógica
Falta de validação de valor negativo na inserção

Link: Linha 18
Descrição: Não há validação para valores negativos ao inserir dinheiro na máquina.
Label: Bug, Implementação
Array de papel moeda não está ordenado corretamente

Link: Linha 14
Descrição: O array papelMoeda não está em ordem decrescente, o que pode afetar a eficiência dos algoritmos de troco.
Label: Melhoria, Implementação
Método imprimir() não está retornando o troco

Link: Linha 37
Descrição: O método imprimir() apenas retorna o ticket, mas não lida com o troco, caso exista.
Label: Melhoria, Implementação
Falta de documentação adequada

Link: Todas as linhas
Descrição: Falta de comentários e documentação adequada para explicar a funcionalidade de cada método e variável.
Label: Melhoria, Documentação

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
