### ISSUE TITLE
return incorreto

### ISSUE THREAD

**Issue by SolangeAlvarenga** [Prof-Calebe/Source-Code-Inspection#21]
classe troco, linha 63 e 66, os returns estão com logica incorreta juntamente com o IF.

@override
public boolean hasNext() {
for (int i = 0; i <= 5; i++) {
if (troco.papeisMoeda[i] = null) {
return false;
}
}
return true;
}

**Comment by calebepb** [comment]
Este comentário deve ser feito no seu repositório.
