### ISSUE TITLE
Validação de Nota Acessando Apenas um Índice do Vetor papelMoeda

### ISSUE THREAD

**Issue by dmsdy** [Prof-Calebe/Source-Code-Inspection#226]
O loop for na função inserir está verificando apenas o índice 1 do array papelMoeda, em vez de comparar o valor correspondente do array (ou seja, papelMoeda[i]) com a quantidade inserida.

```if (papelMoeda[1] == quantia) {```

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário/fix deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
