### ISSUE TITLE
O índice 1 é fixo, mas deveria ser i para verificar corretamente todos os valores do array.

### ISSUE THREAD

**Issue by Arthur230103** [Prof-Calebe/Source-Code-Inspection#237]
Descrição: O índice 1 é fixo, mas deveria ser i para verificar corretamente todos os valores do array.
Classe: TicketMachine
Linha: 25
Criticidade: Alto
Labels: bug, Dados, Alto

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário/fix deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
