### ISSUE TITLE
PAPEL MOEDA

### ISSUE THREAD

**Issue by guimaioli17** [Prof-Calebe/Source-Code-Inspection#42]
package br.calebe.ticketmachine.core;

/**
 *Alunos: Guilherme Maoli e Leonardo Portella
 * @author Calebe de Paula Bianchini
 */
public class PapelMoeda {
    **//Comissao: no lugar do protected deveria ser public - BAIXO**
    protected int valor;
    protected int quantidade;
    **//Construtor - BAIXO**
    public PapelMoeda(int valor, int quantidade) {
        this.valor = valor;
        this.quantidade = quantidade;
    }
   **//Comissao: não foi criado setValor - ALTO**
    public int getValor() {
        return valor;
    }
   **//Comissao: não foi criado setQuantidade - ALTO**
    public int getQuantidade() {
        return quantidade;
    }
}

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
