### ISSUE TITLE
TICKET MACHINE

### ISSUE THREAD

**Issue by guimaioli17** [Prof-Calebe/Source-Code-Inspection#43]
package br.calebe.ticketmachine.core;

import br.calebe.ticketmachine.exception.PapelMoedaInvalidaException;
import br.calebe.ticketmachine.exception.SaldoInsuficienteException;
import java.util.Iterator;

/**
 *Alunos: Guilherme Maoli e Leonardo Portella
 * @author Calebe de Paula Bianchini
 */
public class TicketMachine {

    protected int valor;
    **//Desempenho:nao foi criado saldo ALTO**
    protected int saldo;
    **//Comissao: nao foi criado a classe papelMoeda ALTO**
    protected int[] papelMoeda = {2, 5, 10, 20, 50, 100};
  
    public TicketMachine(int valor) {
        this.valor = valor;
     **//Desempenho:nao foi criado saldo ALTO**
     **//Comissão: deveria ser classe construtor, pois esta chamando o saldo MEDIO**
        this.saldo = 0;
    }

    public void inserir(int quantia) throws PapelMoedaInvalidaException {
        boolean achou = false;
        for (int i = 0; i < papelMoeda.length && !achou; i++) {
            **//DADOS:valor de papelmoeda deve ser i ALTO**
            if (papelMoeda[1] == quantia) {
                achou = true;
            }
        }
        if (!achou) {
            throw new PapelMoedaInvalidaException();
        }
        **//Desempenho:nao foi criado saldo ALTO**
        this.saldo += quantia;
    }
**//Desempenho:nao foi criado saldo ALTO**

    public int getSaldo() {
        return saldo;
    }
**//Excesso: nao foi criado Iterator ALTO**
**//A função "getTroco()" sempre retorna "null" portanto não é necessaria BAIXO**
    public Iterator<Integer> getTroco() {
        return null;
    }
**//Comissão: desnecessario a consulta de saldo nesse caso BAIXO**
    public String imprimir() throws SaldoInsuficienteException {
        **//Desempenho:nao foi criado saldo ALTO**
        if (saldo < valor) {
            throw new SaldoInsuficienteException();
        }
        String result = "*****************\n";
        result += "*** R$ " + saldo + ",00 ****\n";
        result += "*****************\n";
        return result;
    }
}

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
