### ISSUE TITLE
TROCO

### ISSUE THREAD

**Issue by guimaioli17** [Prof-Calebe/Source-Code-Inspection#44]
package br.calebe.ticketmachine.core;

import java.util.Iterator;

/**
 *Alunos: Guilherme Maoli e Leonardo Portella
 * @author Calebe de Paula Bianchini
 */
class Troco {

    protected PapelMoeda[] papeisMoeda;

    public Troco(int valor) {
        papeisMoeda = new PapelMoeda[6];
        int count = 0;
        **//O loop em questão é infinito pois a variavel que o define não é alterada dentro do proprio laço ALTO**
        while (valor % 100 != 0) {
            count++;
        }
        papeisMoeda[5] = new PapelMoeda(100, count);
        count = 0;
        **//O loop em questão é infinito pois a variavel que o define não é alterada dentro do proprio laço ALTO**
        while (valor % 50 != 0) {
            count++;
        }
        papeisMoeda[4] = new PapelMoeda(50, count);
        count = 0;
        **//O loop em questão é infinito pois a variavel que o define não é alterada dentro do proprio laço ALTO**
        while (valor % 20 != 0) {
            count++;
        }
        papeisMoeda[3] = new PapelMoeda(20, count);
        count = 0;
        **//O loop em questão é infinito pois a variavel que o define não é alterada dentro do proprio laço ALTO**
        while (valor % 10 != 0) {
            count++;
        }
        papeisMoeda[2] = new PapelMoeda(10, count);
        count = 0;
        **//O loop em questão é infinito pois a variavel que o define não é alterada dentro do proprio laço ALTO**
        while (valor % 5 != 0) {
            count++;
        }
        papeisMoeda[1] = new PapelMoeda(5, count);
        count = 0;
        while (valor % 2 != 0) {
            count++;
        }
        papeisMoeda[1] = new PapelMoeda(2, count);
    }

    public Iterator<PapelMoeda> getIterator() {
        return new TrocoIterator(this);
    }

    class TrocoIterator implements Iterator<PapelMoeda> {

        protected Troco troco;

        public TrocoIterator(Troco troco) {
            this.troco = troco;
        }

        @Override
        public boolean hasNext() {
            for (int i = 6; i >= 0; i++) {
                **//O codigo nunca entrara no laço for pois a variavel RET sempre sera NULL ALTO**
                if (troco.papeisMoeda[i] != null) {
                    return true;
                }
            }
            return false;
        }

        @Override
        public PapelMoeda next() {
            PapelMoeda ret = null;
            for (int i = 6; i >= 0 && ret != null; i++) {
                if (troco.papeisMoeda[i] != null) {
                    ret = troco.papeisMoeda[i];
                    troco.papeisMoeda[i] = null;
                }
            }
            return ret;
        }

        @Override
        **//O metodo "remove()" não é necessário pois apenas chama um outro metodo BAIXO**
        public void remove() {
            next();
        }
    }
}

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
