### ISSUE TITLE
TICKET MACHINE - INSPEÇÃO

### ISSUE THREAD

**Issue by MyrddinEmrys** [Prof-Calebe/Source-Code-Inspection#6]
1-) Engenharia de Requisitos
> As estações de trem freqüentemente fornecem máquinas de vender bilhetes que imprimem um bilhete quando um cliente insere a quantia correta para pagar a passagem. As máquinas mantêm uma soma total da quantidade de dinheiro que coletou durante toda sua operação.

**Tipo de Defeito: Ambiguidade**
As máquinas que vendem bilhete são atendidas por atendentes. Voce ate pode ter fazer recarga de bihete sozinho numa licenciada, mas vc nunca compra o cartão (bilhete )neste tipo de maquina.

1.2-) Diagrama dos Casos de Uso
**Tipo de Defeito: Fato Incorreto**
Primeiro insiro o bilhete, depois solicito a quantia, a opção de pagamento e após pago, recebo uma autenticação confirmando o processo. A opção troco teria que ser confirmada no inicio do processo se existe, porque se o processo é concluído e não há troco e o cliente fica sem.

1.3.1-) CSU01 – Inserir dinheiro
> Uma quantia de dinheiro é inserida na máquina. É importante ressaltar que essa quantia sempre é representada por uma única nota de papel-moeda.

**Tipo de Defeito: Fato Incorreto**
O sistema tem que deixar claro se há no troco, se ele só da a opção de dinheiro em uma nota ele tem que me garantir que vou ter meu troco se precisar. Outra opção que seria ideal ter e não há, é o pagamento em cartão de débito, funciona como dinheiro à vista.

> 1. O Cliente insere uma nota de papel- moeda.

**Tipo de Defeito: Fato Incorreto** 
A primeira opção deveria ser validar o bilhete e assim pedir a forma de pagamento. Feito esse processo voce paga e valida o pagamento.

> 4. O Sistema adiciona o valor ao saldo disponível.
> 5. O Sistema informa que a nota de papel- moeda foi aceita.

**Tipo de Defeito: Fato Incorreto** 
Voce paga, depois o sistema deve validar esse pagamento. Confirmado, ai sim o sistema adiciona o valor ao saldo disponível e informa ele, assim finalizar a operação.

> 1. O Sistema devolve a nota de papel- moeda.

**Tipo de Defeito: Fato Incorreto** 
O sistema teria que validar primeiramente se a nota é verdadeira ou falsa.

1.4 Protótipos  > 1.4.1 Tela principal

**Tipo de Defeito: Fato Incorreto** 
Deveria ter a opção de corrigir caso haja necessidade.

2 Projeto Orientado a Objetos > 2.1 Diagrama de Classes Principal

**Tipo de Defeito: Ambiguidade**
Qual a real necessidade do Iterator no diagrama, possivelmente seria para caso o troco seja numa nota que não exista.

**Comment by calebepb** [comment]
Essa issue não é minha. Portanto, não será corrigida!
