### ISSUE TITLE
Na classe TickectMachine a condição dentro do metodo inserir esta incorreta

### ISSUE THREAD

**Issue by RafaelSanzio0** [Prof-Calebe/Source-Code-Inspection#71]
no caso ele verifica o valor apenas da pos 1 do vetor em quanto o correto seria dentre todas as posicoes.

**Comment by RafaelSanzio0** [comment]
no caso ele verifica o valor apenas da pos 1 do vetor em quanto o correto seria dentre todas as posicoes.

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
