### ISSUE TITLE
Defeito no TicketMachine.java

### ISSUE THREAD

**Issue by leonardoabe** [Prof-Calebe/Source-Code-Inspection#77]
Índice de papelMoeda
https://github.com/Prof-Calebe/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java#L24

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
