### ISSUE TITLE
Defeito 1 TicketMachine

### ISSUE THREAD

**Issue by CaahhMack** [Prof-Calebe/Source-Code-Inspection#81]
Erro no código: o ínice do papel moeda esta errado

https://github.com/Prof-Calebe/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java#L25

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
