### ISSUE TITLE
class TicketMachine 1

### ISSUE THREAD

**Issue by miuccya** [Prof-Calebe/Source-Code-Inspection#89]
public class TicketMachine {
    

    protected int valor;
    protected int saldo;
    protected int[] papelMoeda = {2, 5, 10, 20, 50, 100};
    
 /**
     * index do array de maneira correta, sem a posição 6, o valor de 0 à papelMoeda.length - 1 (6)
     * Erro: Dados
     */

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
