### ISSUE TITLE
class TicketMachine 2

### ISSUE THREAD

**Issue by miuccya** [Prof-Calebe/Source-Code-Inspection#90]
public Iterator<Integer> getTroco() {
        return null;
    }

    public String imprimir() throws SaldoInsuficienteException {
        if (saldo < valor) {
            throw new SaldoInsuficienteException();
        }
        String result = "*****************\n";
        result += "*** R$ " + saldo + ",00 ****\n";
        result += "*****************\n";
        return result;
    }
    
 /**
     * Método com ter a verificação parece estar no lugar errado
     * Erro: Computação
     */

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
