### ISSUE TITLE
class PapelMoeda

### ISSUE THREAD

**Issue by miuccya** [Prof-Calebe/Source-Code-Inspection#93]
public class PapelMoeda {

    
    protected int valor;
    protected int quantidade;

    public PapelMoeda(int valor, int quantidade) {
        this.valor = valor;
        this.quantidade = quantidade;
    }

    public int getValor() {
        return valor;
    }

    public int getQuantidade() {
        return quantidade;
    }
}

/**
* Os atributos condigentes com a documentação
* Erro: Omissão
*/

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
