### ISSUE TITLE
Class TicketMachine 3

### ISSUE THREAD

**Issue by miuccya** [Prof-Calebe/Source-Code-Inspection#94]
public class TicketMachine {

    protected int valor;
    protected int saldo;
    protected int[] papelMoeda = {2, 5, 10, 20, 50, 100};
    
     /**
     * Os Atributos não estão especificados na documentação
     * Erro: Omissão
     */

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu repositório.
