### ISSUE TITLE
DefeitoPapelMoeda.java01

### ISSUE THREAD

**Issue by BiancaMMatos** [Prof-Calebe/Source-Code-Inspection#98]
https://github.com/Prof-Calebe/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/PapelMoeda.java#L12

Variável "Quantidade" não está possuindo  atribuição de valores.

**Comment by calebepb** [comment]
Agradeço a colaboração, mas este comentário deve ser feito em outro lugar ou, até mesmo, no seu próprio repositório.
